<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class ContentShkolaSeeder extends Seeder
{
    public function run()
    {
        // НАСТРОЙКИ
        DB::table('settings')->where('id', '1')->update([
            'theme' => 'shkola',
            'orientation' => 'square',
            'title' => 'Школа №1',
            'logo' => '/img/shkola/logo.png',
            'module_news_sort' => '02',
            'module_routes_sort' => '03',
            'module_reviews_sort' => '08',
            'module_photoalbums_sort' => '04',
        ]);

        // СТРАНИЦЫ
        DB::table('pages')->insert([
        [
            'id' => '1',
            'sort' => '07',
            'title' => 'Информация о школе',
            'text' => '',
            'image' => NULL,
            'gallery' => NULL,
            'image_as_icon' => '0',
            'pdf' => NULL,
            'excel' => NULL,
            'parent_id' => NULL,
            'created_at' => '2021-03-14 00:00:00'
        ],
        [
            'id' => '2',
            'sort' => NULL,
            'title' => 'Лицензия',
            'text' => '',
            'image' => NULL,
            'gallery' => NULL,
            'image_as_icon' => '0',
            'pdf' => '/img/med/lic.pdf',
            'excel' => NULL,
            'parent_id' => '1',
            'created_at' => '2021-03-15 00:00:00'
        ],
        [
            'id' => '3',
            'sort' => '04',
            'title' => 'Учителя',
            'text' => '',
            'image' => NULL,
            'gallery' => NULL,
            'image_as_icon' => '0',
            'pdf' => NULL,
            'excel' => NULL,
            'parent_id' => NULL,
            'created_at' => '2021-03-15 00:00:00'
        ],
        [
            'id' => '4',
            'sort' => NULL,
            'title' => 'Математика',
            'text' => '',
            'image' => NULL,
            'gallery' => NULL,
            'image_as_icon' => '0',
            'pdf' => NULL,
            'excel' => NULL,
            'parent_id' => '3',
            'created_at' => '2021-03-15 00:00:00'
        ],
        [
            'id' => '5',
            'sort' => NULL,
            'title' => 'Физика',
            'text' => '',
            'image' => NULL,
            'gallery' => NULL,
            'image_as_icon' => '0',
            'pdf' => NULL,
            'excel' => NULL,
            'parent_id' => '3',
            'created_at' => '2021-03-15 00:00:00'
        ],
        [
            'id' => '6',
            'sort' => NULL,
            'title' => 'Химия',
            'text' => '',
            'image' => NULL,
            'gallery' => NULL,
            'image_as_icon' => '0',
            'pdf' => NULL,
            'excel' => NULL,
            'parent_id' => '3',
            'created_at' => '2021-03-15 00:00:00'
        ],
        [
            'id' => '7',
            'sort' => NULL,
            'title' => 'Русский язык',
            'text' => '',
            'image' => NULL,
            'gallery' => NULL,
            'image_as_icon' => '0',
            'pdf' => NULL,
            'excel' => NULL,
            'parent_id' => '3',
            'created_at' => '2021-03-15 00:00:00'
        ],
        [
            'id' => '8',
            'sort' => NULL,
            'title' => 'Литература',
            'text' => '',
            'image' => NULL,
            'gallery' => NULL,
            'image_as_icon' => '0',
            'pdf' => NULL,
            'excel' => NULL,
            'parent_id' => '3',
            'created_at' => '2021-03-15 00:00:00'
        ],
        [
            'id' => '9',
            'sort' => NULL,
            'title' => 'Иванова Мария Ивановна',
            'text' => '<p>Текст об учителе.</p>',
            'image' => '/img/no-image.jpg',
            'gallery' => NULL,
            'image_as_icon' => '1',
            'pdf' => NULL,
            'excel' => NULL,
            'parent_id' => '4',
            'created_at' => '2021-03-15 00:00:00'
        ],
        [
            'id' => '10',
            'sort' => NULL,
            'title' => 'Петров Петр Петрович',
            'text' => '<p>Текст об учителе.</p>',
            'image' => '/img/no-image.jpg',
            'gallery' => NULL,
            'image_as_icon' => '1',
            'pdf' => NULL,
            'excel' => NULL,
            'parent_id' => '5',
            'created_at' => '2021-03-15 00:00:00'
        ],
        [
            'id' => '11',
            'sort' => NULL,
            'title' => 'Васильева Наталья Юрьевна',
            'text' => '<p>Текст об учителе.</p>',
            'image' => '/img/no-image.jpg',
            'gallery' => NULL,
            'image_as_icon' => '1',
            'pdf' => NULL,
            'excel' => NULL,
            'parent_id' => '6',
            'created_at' => '2021-03-15 00:00:00'
        ],
        [
            'id' => '12',
            'sort' => NULL,
            'title' => 'Степанов Степан Степанович',
            'text' => '<p>Текст об учителе.</p>',
            'image' => '/img/no-image.jpg',
            'gallery' => NULL,
            'image_as_icon' => '1',
            'pdf' => NULL,
            'excel' => NULL,
            'parent_id' => '7',
            'created_at' => '2021-03-15 00:00:00'
        ],
        [
            'id' => '13',
            'sort' => NULL,
            'title' => 'Морозова Любовь Александровна',
            'text' => '<p>Текст об учителе.</p>',
            'image' => '/img/no-image.jpg',
            'gallery' => NULL,
            'image_as_icon' => '1',
            'pdf' => NULL,
            'excel' => NULL,
            'parent_id' => '8',
            'created_at' => '2021-03-15 00:00:00'
        ],
        [
            'id' => '14',
            'sort' => '01',
            'title' => 'Расписание',
            'text' => '',
            'image' => NULL,
            'gallery' => NULL,
            'image_as_icon' => '0',
            'pdf' => NULL,
            'excel' => NULL,
            'parent_id' => NULL,
            'created_at' => '2021-03-15 00:00:00'
        ],
        [
            'id' => '15',
            'sort' => NULL,
            'title' => '5А',
            'text' => '',
            'image' => NULL,
            'gallery' => NULL,
            'image_as_icon' => '0',
            'pdf' => NULL,
            'excel' => '/img/excel.xlsx',
            'parent_id' => '14',
            'created_at' => '2021-03-15 00:00:00'
        ],
        [
            'id' => '16',
            'sort' => NULL,
            'title' => '5Б',
            'text' => '',
            'image' => NULL,
            'gallery' => NULL,
            'image_as_icon' => '0',
            'pdf' => NULL,
            'excel' => '/img/excel.xlsx',
            'parent_id' => '14',
            'created_at' => '2021-03-15 00:00:00'
        ],
        [
            'id' => '17',
            'sort' => NULL,
            'title' => '6А',
            'text' => '',
            'image' => NULL,
            'gallery' => NULL,
            'image_as_icon' => '0',
            'pdf' => NULL,
            'excel' => '/img/excel.xlsx',
            'parent_id' => '14',
            'created_at' => '2021-03-15 00:00:00'
        ],
        [
            'id' => '18',
            'sort' => NULL,
            'title' => '6В',
            'text' => '',
            'image' => NULL,
            'gallery' => NULL,
            'image_as_icon' => '0',
            'pdf' => NULL,
            'excel' => '/img/excel.xlsx',
            'parent_id' => '14',
            'created_at' => '2021-03-15 00:00:00'
        ],
        [
            'id' => '19',
            'sort' => NULL,
            'title' => '7А',
            'text' => '',
            'image' => NULL,
            'gallery' => NULL,
            'image_as_icon' => '0',
            'pdf' => NULL,
            'excel' => '/img/excel.xlsx',
            'parent_id' => '14',
            'created_at' => '2021-03-15 00:00:00'
        ],
        ]);

        // СТРАНИЦЫ->ТИПЫ_СТРАНИЦ
        DB::table('page_type')->insert([
            [
                'page_id' => '1',
                'type_id' => '6',
            ],
            [
                'page_id' => '3',
                'type_id' => '6',
            ],
            [
                'page_id' => '4',
                'type_id' => '6',
            ],
            [
                'page_id' => '5',
                'type_id' => '6',
            ],
            [
                'page_id' => '6',
                'type_id' => '6',
            ],
            [
                'page_id' => '7',
                'type_id' => '6',
            ],
            [
                'page_id' => '8',
                'type_id' => '6',
            ],
            [
                'page_id' => '2',
                'type_id' => '7',
            ],
            [
                'page_id' => '9',
                'type_id' => '2',
            ],
            [
                'page_id' => '10',
                'type_id' => '2',
            ],
            [
                'page_id' => '11',
                'type_id' => '2',
            ],
            [
                'page_id' => '12',
                'type_id' => '2',
            ],
            [
                'page_id' => '13',
                'type_id' => '2',
            ],
            [
                'page_id' => '14',
                'type_id' => '6',
            ],
            [
                'page_id' => '15',
                'type_id' => '9',
            ],
            [
                'page_id' => '16',
                'type_id' => '9',
            ],
            [
                'page_id' => '17',
                'type_id' => '9',
            ],
            [
                'page_id' => '18',
                'type_id' => '9',
            ],
            [
                'page_id' => '19',
                'type_id' => '9',
            ],
            ]);


        // НОВОСТИ
        DB::table('news')->insert([
            [
                'title' => 'Тестовая новость',
                'text' => 'Текст новости 1 - Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Ciceros De Finibus Bonorum et Malorum for use in a type specimen book.',
                'image' => '/img/_2.jpg',
                'created_at' => '2020-10-10 00:00:00'
            ],
            ]);

        // СХЕМЫ
        DB::table('schemes')->insert([
            [
            'id' => '1',
            'title' => 'Этаж 1',
            'image' => '/img/med/plan01.png',
            ],
            [
            'id' => '2',
            'title' => 'Этаж 2',
            'image' => '/img/med/plan02.png',
            ],
            [
            'id' => '3',
            'title' => 'Этаж 3',
            'image' => '/img/med/plan03.png',
            ],
        ]);

        // МАРШРУТЫ
        DB::table('r01routes')->insert([
            [
                "created_at" => "2021-03-22 09:50:40",
                "id" => 1,
                "p_x_01" => null,
                "p_x_02" => "497",
                "p_x_03" => "410",
                "p_x_04" => null,
                "p_x_05" => null,
                "p_x_06" => null,
                "p_x_07" => null,
                "p_x_08" => null,
                "p_x_09" => null,
                "p_x_10" => null,
                "p_x_101" => null,
                "p_x_102" => null,
                "p_x_103" => null,
                "p_x_104" => null,
                "p_x_105" => null,
                "p_x_106" => null,
                "p_x_107" => null,
                "p_x_108" => null,
                "p_x_109" => null,
                "p_x_11" => null,
                "p_x_110" => null,
                "p_x_111" => null,
                "p_x_112" => null,
                "p_x_12" => null,
                "p_y_01" => null,
                "p_y_02" => "197",
                "p_y_03" => "200",
                "p_y_04" => null,
                "p_y_05" => null,
                "p_y_06" => null,
                "p_y_07" => null,
                "p_y_08" => null,
                "p_y_09" => null,
                "p_y_10" => null,
                "p_y_101" => null,
                "p_y_102" => null,
                "p_y_103" => null,
                "p_y_104" => null,
                "p_y_105" => null,
                "p_y_106" => null,
                "p_y_107" => null,
                "p_y_108" => null,
                "p_y_109" => null,
                "p_y_11" => null,
                "p_y_110" => null,
                "p_y_111" => null,
                "p_y_112" => null,
                "p_y_12" => null,
                "scheme2_id" => "Выберите второй план",
                "scheme_id" => "1",
                "t_1_begin" => "Вы здесь",
                "t_1_end" => "Вы пришли",
                "t_2_begin" => "Вы здесь",
                "t_2_end" => "Вы пришли",
                "title" => "Кабинет №1 - Математика",
                "updated_at" => "2021-03-22 09:50:40",
                "x_01" => "497",
                "x_02" => "410",
                "x_03" => "404",
                "x_04" => null,
                "x_05" => null,
                "x_06" => null,
                "x_07" => null,
                "x_08" => null,
                "x_09" => null,
                "x_10" => null,
                "x_101" => null,
                "x_102" => null,
                "x_103" => null,
                "x_104" => null,
                "x_105" => null,
                "x_106" => null,
                "x_107" => null,
                "x_108" => null,
                "x_109" => null,
                "x_11" => null,
                "x_110" => null,
                "x_111" => null,
                "x_112" => null,
                "x_12" => null,
                "y_01" => "197",
                "y_02" => "200",
                "y_03" => "236",
                "y_04" => null,
                "y_05" => null,
                "y_06" => null,
                "y_07" => null,
                "y_08" => null,
                "y_09" => null,
                "y_10" => null,
                "y_101" => null,
                "y_102" => null,
                "y_103" => null,
                "y_104" => null,
                "y_105" => null,
                "y_106" => null,
                "y_107" => null,
                "y_108" => null,
                "y_109" => null,
                "y_11" => null,
                "y_110" => null,
                "y_111" => null,
                "y_112" => null,
                "y_12" => null
            ],
            [
                "created_at" => "2021-03-22 09:53:16",
                "id" => 2,
                "p_x_01" => null,
                "p_x_02" => "498",
                "p_x_03" => "358",
                "p_x_04" => null,
                "p_x_05" => null,
                "p_x_06" => null,
                "p_x_07" => null,
                "p_x_08" => null,
                "p_x_09" => null,
                "p_x_10" => null,
                "p_x_101" => null,
                "p_x_102" => null,
                "p_x_103" => null,
                "p_x_104" => null,
                "p_x_105" => null,
                "p_x_106" => null,
                "p_x_107" => null,
                "p_x_108" => null,
                "p_x_109" => null,
                "p_x_11" => null,
                "p_x_110" => null,
                "p_x_111" => null,
                "p_x_112" => null,
                "p_x_12" => null,
                "p_y_01" => null,
                "p_y_02" => "196",
                "p_y_03" => "202",
                "p_y_04" => null,
                "p_y_05" => null,
                "p_y_06" => null,
                "p_y_07" => null,
                "p_y_08" => null,
                "p_y_09" => null,
                "p_y_10" => null,
                "p_y_101" => null,
                "p_y_102" => null,
                "p_y_103" => null,
                "p_y_104" => null,
                "p_y_105" => null,
                "p_y_106" => null,
                "p_y_107" => null,
                "p_y_108" => null,
                "p_y_109" => null,
                "p_y_11" => null,
                "p_y_110" => null,
                "p_y_111" => null,
                "p_y_112" => null,
                "p_y_12" => null,
                "scheme2_id" => "Выберите второй план",
                "scheme_id" => "1",
                "t_1_begin" => "Вы здесь",
                "t_1_end" => "Вы пришли",
                "t_2_begin" => "Вы здесь",
                "t_2_end" => "Вы пришли",
                "title" => "Кабинет №2 - Русский язык",
                "updated_at" => "2021-03-22 09:53:16",
                "x_01" => "498",
                "x_02" => "358",
                "x_03" => "348",
                "x_04" => null,
                "x_05" => null,
                "x_06" => null,
                "x_07" => null,
                "x_08" => null,
                "x_09" => null,
                "x_10" => null,
                "x_101" => null,
                "x_102" => null,
                "x_103" => null,
                "x_104" => null,
                "x_105" => null,
                "x_106" => null,
                "x_107" => null,
                "x_108" => null,
                "x_109" => null,
                "x_11" => null,
                "x_110" => null,
                "x_111" => null,
                "x_112" => null,
                "x_12" => null,
                "y_01" => "196",
                "y_02" => "202",
                "y_03" => "236",
                "y_04" => null,
                "y_05" => null,
                "y_06" => null,
                "y_07" => null,
                "y_08" => null,
                "y_09" => null,
                "y_10" => null,
                "y_101" => null,
                "y_102" => null,
                "y_103" => null,
                "y_104" => null,
                "y_105" => null,
                "y_106" => null,
                "y_107" => null,
                "y_108" => null,
                "y_109" => null,
                "y_11" => null,
                "y_110" => null,
                "y_111" => null,
                "y_112" => null,
                "y_12" => null
            ],
            [
                "created_at" => "2021-03-22 09:55:36",
                "id" => 3,
                "p_x_01" => null,
                "p_x_02" => "497",
                "p_x_03" => "454",
                "p_x_04" => null,
                "p_x_05" => null,
                "p_x_06" => null,
                "p_x_07" => null,
                "p_x_08" => null,
                "p_x_09" => null,
                "p_x_10" => null,
                "p_x_101" => null,
                "p_x_102" => "467",
                "p_x_103" => "468",
                "p_x_104" => "407",
                "p_x_105" => null,
                "p_x_106" => null,
                "p_x_107" => null,
                "p_x_108" => null,
                "p_x_109" => null,
                "p_x_11" => null,
                "p_x_110" => null,
                "p_x_111" => null,
                "p_x_112" => null,
                "p_x_12" => null,
                "p_y_01" => null,
                "p_y_02" => "196",
                "p_y_03" => "196",
                "p_y_04" => null,
                "p_y_05" => null,
                "p_y_06" => null,
                "p_y_07" => null,
                "p_y_08" => null,
                "p_y_09" => null,
                "p_y_10" => null,
                "p_y_101" => null,
                "p_y_102" => "99",
                "p_y_103" => "253",
                "p_y_104" => "253",
                "p_y_105" => null,
                "p_y_106" => null,
                "p_y_107" => null,
                "p_y_108" => null,
                "p_y_109" => null,
                "p_y_11" => null,
                "p_y_110" => null,
                "p_y_111" => null,
                "p_y_112" => null,
                "p_y_12" => null,
                "scheme2_id" => "2",
                "scheme_id" => "1",
                "t_1_begin" => "Вы здесь",
                "t_1_end" => "Лестница, эт. 2",
                "t_2_begin" => "От лестницы",
                "t_2_end" => "Вы пришли",
                "title" => "Кабинет директора",
                "updated_at" => "2021-03-22 09:55:36",
                "x_01" => "497",
                "x_02" => "454",
                "x_03" => "455",
                "x_04" => null,
                "x_05" => null,
                "x_06" => null,
                "x_07" => null,
                "x_08" => null,
                "x_09" => null,
                "x_10" => null,
                "x_101" => "467",
                "x_102" => "468",
                "x_103" => "407",
                "x_104" => "406",
                "x_105" => null,
                "x_106" => null,
                "x_107" => null,
                "x_108" => null,
                "x_109" => null,
                "x_11" => null,
                "x_110" => null,
                "x_111" => null,
                "x_112" => null,
                "x_12" => null,
                "y_01" => "196",
                "y_02" => "196",
                "y_03" => "94",
                "y_04" => null,
                "y_05" => null,
                "y_06" => null,
                "y_07" => null,
                "y_08" => null,
                "y_09" => null,
                "y_10" => null,
                "y_101" => "99",
                "y_102" => "253",
                "y_103" => "253",
                "y_104" => "292",
                "y_105" => null,
                "y_106" => null,
                "y_107" => null,
                "y_108" => null,
                "y_109" => null,
                "y_11" => null,
                "y_110" => null,
                "y_111" => null,
                "y_112" => null,
                "y_12" => null
            ],
            [
                "created_at" => "2021-03-22 09:59:03",
                "id" => 4,
                "p_x_01" => null,
                "p_x_02" => "498",
                "p_x_03" => "456",
                "p_x_04" => null,
                "p_x_05" => null,
                "p_x_06" => null,
                "p_x_07" => null,
                "p_x_08" => null,
                "p_x_09" => null,
                "p_x_10" => null,
                "p_x_101" => null,
                "p_x_102" => "461",
                "p_x_103" => "460",
                "p_x_104" => "338",
                "p_x_105" => null,
                "p_x_106" => null,
                "p_x_107" => null,
                "p_x_108" => null,
                "p_x_109" => null,
                "p_x_11" => null,
                "p_x_110" => null,
                "p_x_111" => null,
                "p_x_112" => null,
                "p_x_12" => null,
                "p_y_01" => null,
                "p_y_02" => "198",
                "p_y_03" => "196",
                "p_y_04" => null,
                "p_y_05" => null,
                "p_y_06" => null,
                "p_y_07" => null,
                "p_y_08" => null,
                "p_y_09" => null,
                "p_y_10" => null,
                "p_y_101" => null,
                "p_y_102" => "105",
                "p_y_103" => "250",
                "p_y_104" => "255",
                "p_y_105" => null,
                "p_y_106" => null,
                "p_y_107" => null,
                "p_y_108" => null,
                "p_y_109" => null,
                "p_y_11" => null,
                "p_y_110" => null,
                "p_y_111" => null,
                "p_y_112" => null,
                "p_y_12" => null,
                "scheme2_id" => "2",
                "scheme_id" => "1",
                "t_1_begin" => "Вы здесь",
                "t_1_end" => "Лестница, эт. 2",
                "t_2_begin" => "От лестницы",
                "t_2_end" => "Вы пришли",
                "title" => "Кабинет завуча",
                "updated_at" => "2021-03-22 09:59:03",
                "x_01" => "498",
                "x_02" => "456",
                "x_03" => "454",
                "x_04" => null,
                "x_05" => null,
                "x_06" => null,
                "x_07" => null,
                "x_08" => null,
                "x_09" => null,
                "x_10" => null,
                "x_101" => "461",
                "x_102" => "460",
                "x_103" => "338",
                "x_104" => "337",
                "x_105" => null,
                "x_106" => null,
                "x_107" => null,
                "x_108" => null,
                "x_109" => null,
                "x_11" => null,
                "x_110" => null,
                "x_111" => null,
                "x_112" => null,
                "x_12" => null,
                "y_01" => "198",
                "y_02" => "196",
                "y_03" => "88",
                "y_04" => null,
                "y_05" => null,
                "y_06" => null,
                "y_07" => null,
                "y_08" => null,
                "y_09" => null,
                "y_10" => null,
                "y_101" => "105",
                "y_102" => "250",
                "y_103" => "255",
                "y_104" => "293",
                "y_105" => null,
                "y_106" => null,
                "y_107" => null,
                "y_108" => null,
                "y_109" => null,
                "y_11" => null,
                "y_110" => null,
                "y_111" => null,
                "y_112" => null,
                "y_12" => null
            ],
        ]);
    }
}
